networks:
  proxy-netz:
    external: true

services:
  app:
    container_name: visionary-px-studio-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        GEMINI_API_KEY: ${GEMINI_API_KEY}

    restart: always
    ports:
      - "${APP_PORT:-3000}:80"
    networks:
      - proxy-netz
    env_file:
      - .env
