import { Router } from 'express';
import clientRoutes from './clients';
import projectRoutes from './projects';
import taskRoutes from './tasks';
import timeEntryRoutes from './timeEntries';
import storageRoutes from './storage';
import profileRoutes from './profiles';
import notificationRoutes from './notifications';
import assetRoutes from './assets';
import clientContactRoutes from './clientContacts';
import workloadRoutes from './workload';
import serviceModuleRoutes from './serviceModules';
import seniorityLevelRoutes from './seniorityLevels';
import reportsRoutes from './reports';
import resourcesRoutes from './resources';
import servicePricingRoutes from './servicePricing';
import documentRoutes from './documents';
import offerRoutes from './offers';

import mocoWebhookRoutes from './mocoWebhooks';
import chatRoutes from './chat';
import directoryFreelancersRoutes from './directoryFreelancers';
import directoryLocationsRoutes from './directoryLocations';
import accountsRoutes from './accounts';
import kitchenDutyRoutes from './kitchenDuty';

const router = Router();

router.use('/clients', clientRoutes);
router.use('/projects', projectRoutes);
router.use('/tasks', taskRoutes);
router.use('/time-entries', timeEntryRoutes);
router.use('/storage', storageRoutes);
router.use('/profiles', profileRoutes);
router.use('/notifications', notificationRoutes);
router.use('/assets', assetRoutes);
router.use('/client-contacts', clientContactRoutes);
router.use('/workload', workloadRoutes);
router.use('/service-modules', serviceModuleRoutes);
router.use('/service-pricing', servicePricingRoutes);
router.use('/seniority-levels', seniorityLevelRoutes);
router.use('/reports', reportsRoutes);
router.use('/resources', resourcesRoutes);
router.use('/documents', documentRoutes);
router.use('/offers', offerRoutes);
router.use('/webhooks/moco', mocoWebhookRoutes);
router.use('/chat', chatRoutes);
router.use('/directory-freelancers', directoryFreelancersRoutes);
router.use('/directory-locations', directoryLocationsRoutes);
router.use('/accounts', accountsRoutes);
router.use('/kitchen-duty', kitchenDutyRoutes);

export default router;
